# Generated by Django 3.1.2 on 2020-11-02 11:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2020, 11, 2, 11, 9, 49, 475441, tzinfo=utc)),
        ),
    ]
