# Generated by Django 3.1.2 on 2020-11-02 11:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20201102_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date_created',
            field=models.DateField(default=datetime.date(2020, 11, 2)),
        ),
    ]
