# Generated by Django 3.1.2 on 2020-11-02 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20201102_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='firm',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
    ]
