# Generated by Django 3.1.2 on 2020-10-28 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='link',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='stagenote',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stagenote', to='pages.application'),
        ),
    ]
