# Generated by Django 3.1.2 on 2020-10-29 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20201028_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='stage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_stage', to='pages.stagenote'),
        ),
        migrations.AlterField(
            model_name='stagenote',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stagenoting', to='pages.application'),
        ),
    ]
