# Generated by Django 3.1.2 on 2020-10-29 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_remove_application_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='stage',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='current_stage', to='pages.stagenote'),
        ),
    ]
