# Generated by Django 3.1.2 on 2020-10-30 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_application_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='stage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_stage', to='pages.stagenote'),
        ),
    ]
