# Generated by Django 3.1.2 on 2020-10-30 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20201030_0022'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes1', models.TextField()),
                ('notes2', models.TextField()),
                ('notes3', models.TextField()),
                ('notes4', models.TextField()),
                ('notes5', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='application',
            name='stage',
            field=models.CharField(choices=[('1', 'Stage 1'), ('2', 'Stage2'), ('3', 'Stage 3'), ('4', 'Stage4'), ('5', 'Stage 5')], max_length=150),
        ),
        migrations.DeleteModel(
            name='StageNote',
        ),
        migrations.AddField(
            model_name='notes',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='pages.application'),
        ),
    ]
