# Generated by Django 3.1.2 on 2020-10-30 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_auto_20201030_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='stage',
            field=models.CharField(choices=[('1', 'Stage 1'), ('2', 'Stage2'), ('3', 'Stage 3'), ('4', 'Stage4'), ('5', 'Stage 5')], default=('1', 'Stage 1'), max_length=150),
        ),
    ]
