# Generated by Django 3.1.2 on 2020-10-30 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_auto_20201030_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='notes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='pages.notes'),
        ),
    ]
