# Generated by Django 3.1.2 on 2020-10-31 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_auto_20201031_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='open_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='stage',
            field=models.CharField(choices=[('Not started', 'Not started'), ('Application submitted', 'Application Submitted'), ('Online tests completed', 'Online tests completed'), ('Phone / Video interview received', 'Phone / Video interview received'), ('Phone / Video interview complete', 'Phone / Video interview complete'), ('Final stage interview received', 'Final stage interview received'), ('Rejected', 'Rejected')], default='Not started', max_length=150),
        ),
        migrations.AlterField(
            model_name='notes',
            name='notes1',
            field=models.TextField(blank=True, default='', verbose_name='Research phase'),
        ),
        migrations.AlterField(
            model_name='notes',
            name='notes2',
            field=models.TextField(blank=True, default='', verbose_name='Phone / Video interview preparation'),
        ),
        migrations.AlterField(
            model_name='notes',
            name='notes3',
            field=models.TextField(blank=True, default='', verbose_name='Phone / Video interview reflections'),
        ),
        migrations.AlterField(
            model_name='notes',
            name='notes4',
            field=models.TextField(blank=True, default='', verbose_name='Final interview preparation'),
        ),
        migrations.AlterField(
            model_name='notes',
            name='notes5',
            field=models.TextField(blank=True, default='', verbose_name='Reflection on job outcome'),
        ),
    ]
