# Generated by Django 3.1.2 on 2020-10-31 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_auto_20201031_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='open_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
