# Generated by Django 3.1.2 on 2020-10-31 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_auto_20201031_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='open_date',
            field=models.DateField(),
        ),
    ]
