# Generated by Django 3.1.2 on 2020-11-01 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_auto_20201031_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='close_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='open_date',
            field=models.DateField(null=True),
        ),
    ]
