# Generated by Django 3.1.2 on 2020-11-04 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0020_auto_20201104_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='job_title',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
