# Generated by Django 3.1.2 on 2020-11-04 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0021_application_job_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='industry',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
