# Generated by Django 3.1.2 on 2020-10-31 18:49

import accounts.helper
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20201031_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='additional_files',
            field=models.FileField(blank=True, null=True, upload_to='', validators=[accounts.helper.file_size]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='number',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='Phone Number'),
        ),
    ]
